package pdfwatermark;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Main window.
 * 
 * @author Prof. Dr. David Buzatto
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInput = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        lblOutput = new javax.swing.JLabel();
        txtOutput = new javax.swing.JTextField();
        lblWatermark = new javax.swing.JLabel();
        txtWatermark = new javax.swing.JTextField();
        btnAddWatermark = new javax.swing.JButton();
        btnChooseInput = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDF Watermark POC");

        lblInput.setText("Input file:");

        txtInput.setEditable(false);

        lblOutput.setText("Output file:");

        txtOutput.setEditable(false);

        lblWatermark.setText("Watermark text:");

        txtWatermark.setText("this is just a test...");

        btnAddWatermark.setText("Add Watermark");
        btnAddWatermark.addActionListener(this::btnAddWatermarkActionPerformed);

        btnChooseInput.setText("...");
        btnChooseInput.addActionListener(this::btnChooseInputActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddWatermark)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOutput)
                            .addComponent(lblInput)
                            .addComponent(lblWatermark))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInput)
                            .addComponent(txtWatermark, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChooseInput)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInput)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutput)
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWatermark)
                    .addComponent(txtWatermark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddWatermark)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseInputActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter( new FileNameExtensionFilter( "PDF files", "pdf" ) );

        if ( chooser.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION ) {
            File inputFile = chooser.getSelectedFile();
            txtInput.setText( inputFile.getAbsolutePath() );
            txtOutput.setText( deriveOutputFile( inputFile ).getAbsolutePath() );
        }
        
    }//GEN-LAST:event_btnChooseInputActionPerformed

    private void btnAddWatermarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWatermarkActionPerformed
        
        if ( txtInput.getText().isBlank() ) {
            JOptionPane.showMessageDialog( this, "Choose an input file first.", "PDF Watermark POC", JOptionPane.WARNING_MESSAGE );
            return;
        }

        File inputFile = new File( txtInput.getText() );
        File outputFile = new File( txtOutput.getText() );

        try {
            PdfWatermarker.addWatermark( inputFile, outputFile, txtWatermark.getText() );
            JOptionPane.showMessageDialog( 
                this, 
                "Watermarked file saved to:\n" + outputFile.getAbsolutePath(), 
                "PDF Watermark POC",
                JOptionPane.INFORMATION_MESSAGE
            );
        } catch ( IOException exc ) {
            JOptionPane.showMessageDialog(
                this,
                "Error processing file:\n" + exc.getMessage(),
                "PDF Watermark POC",
                JOptionPane.ERROR_MESSAGE
            );
        }
        
    }//GEN-LAST:event_btnAddWatermarkActionPerformed

    /**
     * Builds the output file for a given input file, placing it in the same
     * directory and appending a "_watermarked" suffix before the extension.
     */
    private static File deriveOutputFile( File inputFile ) {
        String name = inputFile.getName();
        int dot = name.lastIndexOf( '.' );
        String base = dot >= 0 ? name.substring( 0, dot ) : name;
        String ext = dot >= 0 ? name.substring( dot ) : "";
        return new File( inputFile.getParentFile(), base + "_watermarked" + ext );
    }

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        try {
            for ( UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ReflectiveOperationException | UnsupportedLookAndFeelException exc ) {
            exc.printStackTrace();
        }
        SwingUtilities.invokeLater( () -> new MainWindow().setVisible( true ) );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWatermark;
    private javax.swing.JButton btnChooseInput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblWatermark;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOutput;
    private javax.swing.JTextField txtWatermark;
    // End of variables declaration//GEN-END:variables
}
